### PR TITLE
Add -frames option to the Protonect

### PR DESCRIPTION
**Pull request by hanyazou**
this option is convenient for test automation

### CODE REVIEW

**Comment by hanyazou** [comment]
tested on Mac and Linux (Jetson TK1)

**Comment by xlz** [comment]
Manually merged.

I changed int64_t to size_t, and strtoll to strtol (strtoll is C++11).

**Comment by hanyazou** [comment]
@xlz Thank you. But why don't you use the second argument of strtol()? You can't specify zero for the frame count with your change. And strtol may ignore trailing garbage like '-frames 1cl' ('cl' is just ignored). I'm just curious while it might be okey.

**Comment by xlz** [comment]
I didn't think `-frames 0` has any purpose. `-frames 1` can do stress test already.

I was going to use `atoi`, though. I didn't think this needs super strict checking.

**Pull request closed without merging**
