### PR TITLE
Add build script for Android

### PR DESCRIPTION
**Pull request by CismonX**
Add a simple NDK build script for Android support.
Tested on my Hikey 970 board running Android P.

Future support:
* Java bindings.
* OpenGL depth packet processor.

### CODE REVIEW

**Comment by xlz** [comment]
I can merge most of this save for the last bit where you make TurboJPEG optional. It's not optional because you can't dump RGB packets when it's not available. Dumping RGB packets makes the essential function of this library not working.

**Comment by CismonX** [comment]
> I can merge most of this save for the last bit where you make TurboJPEG optional. It's not optional because you can't dump RGB packets when it's not available. Dumping RGB packets makes the essential function of this library not working.

I believe there are cases when you just want to use raw RGB or depth frames without first rendering them to displayable image, such as storing them to files for later processing. Real-time packet processing yields low frame rate on Android devices since many packets have to be discarded due to poor hardware performance.

**Comment by xlz** [comment]
You're changing the default to a dysfunctional configuration. If realtime processing is slow you can opt in for the packet dumper. It's a different question of changing the default.

**Comment by CismonX** [comment]
> You're changing the default to a dysfunctional configuration. If realtime processing is slow you can opt in for the packet dumper. It's a different question of changing the default.

Okay. I've just removed the second commit from the pull request.

**Pull request merged**
