### PR TITLE
Generate depth tables with camera parameters

### PR DESCRIPTION
**Pull request by xlz**
The xtable, ztable, and 11to16 LUT can now be generated with camera parameters at runtime according to analysis in #144. The tables are generated during `Freenect2Device::start()`, and passed to depth processors.

Users can provide custom camera parameters at runtime with new API: `setIrCameraParams()`, and `setColorCameraParams()`, and depth processors will use those instead of USB queried parameters.

File loading functions in depth processors are removed.

Hardcoded table binary files are removed.

### CODE REVIEW

**Comment by floe** [comment]
Excellent work, could you perhaps add a short comment explaining the functionality of xtable/ztable itself (since you've reverse-engineered it now fully)?

**Comment by xlz** [comment]
v2:

* Added comments about 8192 and 6250.0/3 magic numbers
* Added comments about the nature of x/ztable
* Consolidated X/Z/LUTables generation functions into `struct IrCameraTables`.

Old comments can be found here: https://github.com/xlz/libfreenect2/commit/866fdb2dbab42cd7727db3dd52a8260cd964be21

**Comment by xlz** [comment]
Rebased to master.

**Comment by xlz** [comment]
Rebased to master.

**Comment by floe** [comment]
Just tested this, works as expected. Purely from visual inspection, I can't tell any difference between the two versions; I think @wiedemeyer had done some measurements?

**Comment by xlz** [comment]
To tell a difference, extract two frames from before and after, `imagesc(abs(before-after))` will visualize the difference.

To absolutely prove the correctness, another set of x/z/lut tables have to be extracted and compared with tables computed here. Or another round of calibration set with `setIrCameraParams()` with external intrinsic parameters.

**Comment by xlz** [comment]
You might see some patterns obtained in http://designfankhauser.ch/files/fankhauser_2014_kinect_v2.pdf fig 5.

It is possible some of the errors analyzed in the paper come from the discrepancy of the intrinsic parameters used for image warping (external) and depth decoding (hardcoded).

**Comment by xlz** [comment]
diff
This is the absolute error between before and after this patch (pixel values are the average of 100s image, only showing pixels with standard deviation less than 4). 

Histogram of the error between before and after. 
hist

**Comment by floe** [comment]
Ah, this is very interesting - AFAICT, the error distribution means that there wasn't a systematic error before, just a different error distribution?

**Comment by xlz** [comment]
The above plots might not be meaningful. Probably most of it is just noise and not showing the bias.

Here are another two plots showing the theoretical errors in the final depth values between using the hardcoded parameters, and (1) the embedded intrinsic parameters of my Kinect; (2) iai_kinect2's sample intrinsic parameters:

diff1
diff2

I guess this really depends on the particular calibration parameters. At the edge the error is as much as a few millimeters, but another problem is data at the edge has poor reflection and poor reliability so is probably discarded for reliable computation. In the middle the error should be tiny.

**Comment by floe** [comment]
We should get this tested a little more widely, so I'm merging it now.

**Pull request merged**
