### PR TITLE
Tegrajpeg and perf code

### PR DESCRIPTION
**Pull request by xlz**
There are some changes here that may be hard to test. I have tested these quite some time, but I'll give it some days of review.

* Add Tegra JPEG decoder - this performance is better than previously obtained, probably because of general improvement of underlying code
* Make CUDA 6.5 work with C++11 (compile .cu with c++98, and link it with c++11 objects - bad)
* `./Protonect -gpu=1 cl` (when the first gpu is nvidia and it doesn't work)
* Set thread names so it's easier to look at `top` - cross platform code, harder to test
* Print detailed stats for perf

I have put together some benchmark results, check out https://github.com/OpenKinect/libfreenect2/wiki/Performance

### CODE REVIEW

**Comment by xlz** [comment]
Hi Jetson users! The support for TK1 finally arrives in the libfreenect2 upstream, and NEW performace record: 90HZ depth and 80 Hz JPEG!

Call for testing @anshulvj  @YoniSmolin @cretaceous-creature @ibaranov-cp @RyanGordon  @l0g1x @andreykurenkov @wjchen84 @vishu2287 @bingyo

**Comment by cretaceous-creature** [comment]
GJ!

2016-02-18 15:20 GMT+09:00 Lingzhu Xiang <notifications@github.com>:

**Comment by anshulvj** [comment]
Hi Lingzhu,

Do you have a bibtex for your libfreenect2 library?

**Comment by xlz** [comment]
@anshulvj Yes, https://zenodo.org/record/45314/export/hx

**Comment by anshulvj** [comment]
Thanks!

**Pull request merged**
