### PR TITLE
Plug memory leaks

### PR DESCRIPTION
**Pull request by xlz**
These are some major leaks caught with valgrind.

There may be many other small ones. There may be some leaks that happen in graphics drivers. I'm not entirely sure. Comments are needed.

This does not include fixes for leaks in viewer.cpp.

Tested only on Debian right now. Reviews are needed.

### CODE REVIEW

**Comment by ahundt** [comment]
I ran the clang static analyzer in Xcode and got a few minor things there:

```
/Users/athundt/source/git/libfreenect2/examples/viewer.cpp:10:9: Value stored to 'init' during its initialization is never read
/Users/athundt/source/git/libfreenect2/src/cpu_depth_packet_processor.cpp:705:9: Value stored to 't10' is never read
/Users/athundt/source/git/libfreenect2/examples/Protonect.cpp
/Users/athundt/source/git/libfreenect2/examples/Protonect.cpp:141:27: Potential leak of memory pointed to by 'filelogger'
/Users/athundt/source/git/libfreenect2/examples/Protonect.cpp:120:6: Assuming 'executable_name_idx' is equal to 'npos'
/Users/athundt/source/git/libfreenect2/examples/Protonect.cpp:135:30: Memory is allocated
/Users/athundt/source/git/libfreenect2/examples/Protonect.cpp:141:27: Potential leak of memory pointed to by 'filelogger'
```

**Comment by floe** [comment]
@ahundt did you happen to test this PR on MacOS X?

**Comment by ahundt** [comment]
@floe sorry, I actually ran it on bc5c978

**Comment by xlz** [comment]
I think filelogger is fixed in here.

**Comment by xlz** [comment]
Self-review seems fine. I'll merge this into another bigger PR for the ease of testing.

**Comment by floe** [comment]
Mmh. I was hoping to leave this as the very last one for 0.1, what else do you have in mind?

**Comment by xlz** [comment]
#530 Gotta have versions

**Pull request closed without merging**
