### PR TITLE
API documentation

### PR DESCRIPTION
**Pull request by xlz**
Again, only the last two commits are for this PR.

Review generated sample documentation here http://xlz.github.io/libfreenect2/. Feedback and critique are welcome. I also added some styles to doxygen to try to make it look less ugly.

### CODE REVIEW

**Comment by floe** [comment]
+1 great work, thanks! Docs look good to me. I don't currently want to go the whole auto-generation route using Jenkins etc., should be sufficient to generate them locally once and put them into gh-pages branch AFAICT?

**Comment by xlz** [comment]
Yes.

**Comment by xlz** [comment]
Rebased. You can genenerate the docs with version number by `cmake .. -DPROJECT_VERSION=0.1; make doc`. (Ignore the warnings CMP0048)

I don't have a definite idea on how to set up the versioning system right now. That is left for later.

**Comment by xlz** [comment]
Rebased to #479 (one more change is needed for stable ABI).

**Comment by xlz** [comment]
Rebased and tested.

**Pull request merged**
