### PR TITLE
10.8 compatibility

### PR DESCRIPTION
**Pull request by fran6co**
Fixes https://github.com/OpenKinect/libfreenect2/issues/590

### CODE REVIEW

**Comment by xlz** [comment]
Then is VT faster than TurboJPEG?

**Comment by fran6co** [comment]
In my test and according to @RyanGordon it is. Not by much because it's still CPU based. If Apple decides to enable hardware acceleration (because the hardware supports Intel's Quick Sync) it's going to be through this API.

**Comment by xlz** [comment]
Maybe try benchmarking? https://github.com/OpenKinect/libfreenect2/wiki/Performance

**Comment by fran6co** [comment]
I will when I get some time to do it.

**Pull request merged**
