### PR TITLE
opengl: Lower version to 3.2 for older Mac OSX

### PR DESCRIPTION
**Pull request by xlz**
Proposed by @robozo in #519.

### CODE REVIEW

**Comment by floe** [comment]
No side effects on current MacOS?

**Comment by xlz** [comment]
According to GLFW, `glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2)`

> give you a context for the highest version of OpenGL greater than or equal to 3.2 that is supported by your OS and GPU.

So in principle no side effect. @RyanGordon can test this.

**Comment by xlz** [comment]
Tested: Debian, Ubuntu 14.04 with iai_kinect2, Windowss 8.1, Ubuntu 14.04 on Jetson.

**Comment by RyanGordon** [comment]
Sorry for the delay, I can confirm this is indeed working on OSX 10.11.2

**Pull request merged**
