### PR TITLE
0.1 release build system restructuring

### PR DESCRIPTION
**Pull request by xlz**
This implements the source code and build system restructuring in #314 (rename examples/protonect to src), which is intended to the last major PR before 0.1 release. All issues for 0.1 (#233) except x/ztable hardcoding are resolved after this PR.

This PR is rebased on #368 (OpenGL fixes) and #364 (logging system). Commits from #368 and #364 are shown here, but **this PR starts from `Use BUILD_SHARED_LIBS to control library type`**. Commits from other PRs can be commented in their respective PRs.

* `Use BUILD_SHARED_LIBS to control library type` implements static/shared build configuration, requested in #292 and #263, but reverting #276.
* `Allow custom RPATH settings` deprecates libusb embedding #283. Package distributors are now able to specify the custom libusb path to use for libfreenect2.
* `Raise CMake version requirement to 2.18.12.1` fixes a bug #363
* The rest of the commits are about restructuring. They all have distinct descriptions.

There are some ABI changes. I try to minimize the exposed API before the release for forward compatibility. In the commit 2f186a5894988e14f1700f0a70d0e8b55d53a9bf "Separate public and internal API", several headers are moved to an internal header directory and are no longer installed (no change for internal code though).  Protonect in the examples directory can be built with installed libfreenect2: `cd examples; cmake .. -Dfreenect2_DIR=/tmp/libfreenect2/lib/cmake/freenect2; make; ./Protonect`. This will validate the API usage by third-party. And in the commit "Use CMake to generate `LIBFREENECT2_API` macro", symbols become hidden by default, except those explicitly marked with `LIBFREENECT2_API`. Inspecting libfreenect2.so with `nm -g --defined-only -C libfreenect2.so` should reveal only the necessary ones are exported.

This has been tested on Ubuntu/Intel.

I will rebase the PR with updates in the repo.

### CODE REVIEW

**Comment by xlz** [comment]
Rebased to master.

**Comment by floe** [comment]
Sorry, merge conflict with the huge bunch of comments, should be mostly trivial to resolve.

**Comment by xlz** [comment]
@floe no problem. This comes after #383.

**Comment by xlz** [comment]
Rebased to master. Good for review again.

**Comment by floe** [comment]
Seems to work fine for me; can you update the build instructions in the `README`?

**Comment by xlz** [comment]
I just removed `examples/protonect` stuff.

Due to libusb 1.0.20 release (yesterday), there is probably some better way to handle libusb now and some changes about libusb are expected. So I refrained from adding libusb related changes to the docs.

**Comment by floe** [comment]
OK, that's a nice coincidence. I probably won't have a lot of time this week, did you happen to test with libusb-1.0.20 already? Would be great if we could ditch the whole build-this-exact-commit-yourself thing.

**Comment by floe** [comment]
Had a moment to test after all; v1.0.20 does seem to work on Intel USB3 controllers at least. NEC to be tested soon.

**Comment by floe** [comment]
But it's probably a good idea not to mix things up too much; let's merge this soon so we can get it tested and deal with libusb updates at the end.

**Comment by xlz** [comment]
This goes after #391 bug fix.

Not yet with 1.0.20. I will do it soon. But caution is needed. I found a regression in libusb pre-1.0.20 a while ago https://github.com/OpenKinect/libfreenect2/pull/212#issuecomment-98813553. I'll verify if this has been fixed.

I plan to use QEMU with PCI passthrough to test it with Windows and Mac. I'm also busy recently so that still takes some time to set up.

**Comment by xlz** [comment]
Rebased to master after 391.

**Comment by xlz** [comment]
I tried to build this on a Windows 8.1 VM with vfio-pci passthrough of xhci controller. The code did build, but I could not run it because I could not install driver for "Xbox NUI Sensor (composite parent)". Zadig could only find 2 "NuiSensor Adapter" devices.

**Comment by floe** [comment]
I'd say that right now, as long as it builds, we're good to merge.

**Pull request merged**
