### PR TITLE
Fix class LogMessage link error in windows and compile error

### PR DESCRIPTION
**Pull request by yuanmingze**
* Fix class LogMessage link error  in windows 
* Fix logging.cpp's compiling error
* When exit libfreenect2::CpuDepthPacketProcessor::process is called but listener_ pointer is NULL. Adding checking to listener_
* First time deleting not alloced memmory pointer buffer_ will fail.When create Mat buffer_ set NULL

### CODE REVIEW

**Comment by yuanmingze** [comment]
* When exit libfreenect2::CpuDepthPacketProcessor::process is called but listener_ pointer is NULL.
Adding checking to  listener_.
* First time deleting not alloced mem pointer buffer_  will fail.When create Mat buffer_ set NULL and checking when deallocate()

**Comment by floe** [comment]
Looks sensible to me -  @xlz @christiankerl any comments?

**Comment by yuanmingze** [comment]
* The erro reported by MSVC:

> viewer.obj : error LNK2019: unresolved external symbol "public: __cdecl libfreenect2::LogMessage::LogMessage(class libfreenect2::Logger *,enum libfreenect2::Logger::Level)" (??0LogMessage@libfreenect2@@QEAA@PEAVLogger@1@W4Level@21@@Z) referenced in function "public: void __cdecl ShaderProgram::build(void)" (?build@ShaderProgram@@QEAAXXZ)
viewer.obj : error LNK2019: unresolved external symbol "public: __cdecl libfreenect2::LogMessage::~LogMessage(void)" (??1LogMessage@libfreenect2@@QEAA@XZ) referenced in function "public: void __cdecl ShaderProgram::build(void)" (?build@ShaderProgram@@QEAAXXZ)
> viewer.obj : error LNK2019: unresolved external symbol "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl libfreenect2::LogMessage::stream(void)" (?stream@LogMessage@libfreenect2@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function "public: void __cdecl ShaderProgram::build(void)" (?build@ShaderProgram@@QEAAXXZ)
> viewer.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl libfreenect2::getShortName(char const *)" (?getShortName@libfreenect2@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z) referenced in function "public: void __cdecl ShaderProgram::build(void)" (?build@ShaderProgram@@QEAAXXZ)

* I have add the message to commit message
* Thank you for programming advice.

**Comment by xlz** [comment]
OK. The correct fix for this is from a later PR https://github.com/xlz/libfreenect2/commit/ca75ebafabd255a4736fb6179fb786c1e58b3272

Change viewer.h:
```diff
 
 #include <libfreenect2/config.h>
 #include <libfreenect2/frame_listener.hpp>
-#include <libfreenect2/logging.h>
 #include <string>
 #include <map>
 
 #include <../src/flextGL.h>
+#include <iostream>
 #include <GLFW/glfw3.h>
 
 struct Vertex
 @@ -189,7 +189,7 @@ struct ShaderProgram : public WithOpenGLBindings
         {
             gl()->glGetShaderInfoLog(vertex_shader, sizeof(error_buffer), NULL, error_buffer);
 
-            LOG_ERROR << "failed to compile vertex shader!" << std::endl << error_buffer;
+            std::cerr << "failed to compile vertex shader!" << std::endl << error_buffer;
         }
 
         gl()->glCompileShader(fragment_shader);
 @@ -199,7 +199,7 @@ struct ShaderProgram : public WithOpenGLBindings
         {
             gl()->glGetShaderInfoLog(fragment_shader, sizeof(error_buffer), NULL, error_buffer);
 
-            LOG_ERROR << "failed to compile fragment shader!" << std::endl << error_buffer;
+            std::cerr << "failed to compile fragment shader!" << std::endl << error_buffer;
         }
 
         program = gl()->glCreateProgram();
 @@ -213,7 +213,7 @@ struct ShaderProgram : public WithOpenGLBindings
         if (status != GL_TRUE)
         {
             gl()->glGetProgramInfoLog(program, sizeof(error_buffer), NULL, error_buffer);
-            LOG_ERROR << "failed to link shader program!" << std::endl << error_buffer;
+            std::cerr << "failed to link shader program!" << std::endl << error_buffer;
         }
     }
 
```

**Comment by xlz** [comment]
I cleaned up this for you in #385.

* Squashed commit "change CMakeList.txt" with previous one
* Really added commit message for "fix mem free bug and null pointer error"
* Used the correct fix for LogMessage linking error with the above diff.

**Comment by yuanmingze** [comment]
Thank you so much.I'm sorry too late to chanup the the commit.

**Pull request closed without merging**
