### PR TITLE
Build OpenCL program as soon as the OpenCL device is initialized

### PR DESCRIPTION
**Pull request by HenningJ**
Before this, the OpenCL program was built when the first frame arrives and the following frames were dropped, because building the program takes a while.

With this change, the OpenCL program is built before the device is started. Then, when the first frame arrives, it only needs to be initialized, which is quite fast.

When the `DepthPacketProcessor::Config` changes, the OpenCL program might need to be re-initialized or even be rebuilt (depending on which config values were changed), but only the config actually changed. This is handled here as well.

### CODE REVIEW

**Comment by floe** [comment]
Patch looks very sensible, on what platforms has this been tested so far?

**Comment by HenningJ** [comment]
I just tested it on Windows

**Comment by floe** [comment]
Could you merge master into your opencl-build branch again? I don't think this is really a merge conflict, there just have been some minor changes within the OpenCL depth packet processor.

**Comment by HenningJ** [comment]
Done. It was just one little `throw`.

**Comment by floe** [comment]
Finally got around to testing on Ubuntu 14.04, works beautifully. Merged.

**Pull request merged**
