### PR TITLE
Add teapot configuration file

### PR DESCRIPTION
**Pull request by ioquatix**
This is for building this library with teapot (http://teapot.nz). It may need to be updated from time to time.

### CODE REVIEW

**Comment by floe** [comment]
Didn't know about teapot before; how does it deal with installing prerequisites (libusb etc.)?

**Comment by ioquatix** [comment]
So, this is an initial package file to get the ball rolling.

Ideally, teapot builds are idempotent, so it would explicitly specify all dependencies and they could be locked to specific versions. Right now, teapot is just invoking `cmake` directly so all dependencies must be managed by the host OS package manager.

**Comment by ioquatix** [comment]
I'm currently throwing around the ideas of having teapot directly interact with CMake and also have a semi-official centralised repository of packages. I don't like reinventing the wheel though, but teapot does require packages to supply build rules unlike, say, CMake which has them built in, or Make which doesn't really. Because this requirement of packages to supply build rules which in general are usually common for many scenarios it might make sense to share them in an organised way.

Adding dependencies is really easy but if you want to go down that route I'd suggest using teapot to build the entire project and avoid the dependency on CMake for the teapot build. If you'd like to explore this option let me know.

**Comment by ioquatix** [comment]
I'm no longer interested in this and it's out of date.

**Pull request closed without merging**
