### PR TITLE
add basic Registration class

### PR DESCRIPTION
**Pull request by floe**
I've announced my intent to write this a while ago in #41, now I've finally gotten around to an initial implementation. Thanks again to @sh0 for the hard work and M. Vasileiadis for testing the unfinished code.

### CODE REVIEW

**Comment by floe** [comment]
@christiankerl @wiedemeyer I will probably merge this soon-ish into master, as it doesn't currently affect any existing code. For future PRs which actually use the Registration class, I will wait for your input.

**Comment by larshg** [comment]
Hi @floe 

I tried out the registration class - you can see my changes here (There are also some other changes, but nevermind those):

https://github.com/larshg/libfreenect2/tree/registration

Example here:
image

There are some artifacts when there is two objects in the view, making a subshadow of the closest object - I'm not sure why this is happening...

Is the intention that the registration class should be used "outside" libfreenect2 or should it be used inside, as to create a ColoredDepthFrame producer, which you can add a listener to like with the RGB, ir and Depth?

Are there any reason why you do the undistort_depth in two for loops? and is it the intention that the undistort map should be used somewhere else?

To be honest, I'm not that familiar with the multiple view geometry - so I'll try to read it up a bit :)

**Comment by floe** [comment]
Thanks for testing! I don't quite understand what you mean by "subshadow", screenshot looks correct to me?

I would indeed like to create another class of FrameListener, and hopefully take advantage of OpenGL/CL acceleration, too. However, I'm currently a bit swamped with work, so this might take a while... for the moment, it's therefore probably easiest to just merge most of your test code into the apply() method and give people the opportunity to call it on their own.

Calling undistort_depth twice is useless, you're right. However, I'd like to keep the undistortion table separately and add a method to _only_ perform undistortion without depth-color mapping.

**Comment by lolz0r** [comment]
I pulled and built from larshg's fork (https://github.com/larshg/libfreenect2/tree/registration). Cool stuff! However, I still see misalignment as seen in this screenshot:
misalignment

This being said I see similar artifacting when using the official kinect SDK. This leads me to believe that some kind of damage / error has occurred to my kinect hardware causing it to deviate from the factory calibrated values.

Is there anyway to recalibrate the values needed for the registration system using something like: (https://github.com/code-iai/iai_kinect2/tree/master/kinect2_calibration) ?

I went ahead and built the iai_kinect2 calibration tool and was able to generate calibration values. It makes YAML files with contents like:

%YAML:1.0
cameraMatrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.0678176639391463e+03, 0., 9.8017834376380301e+02, 0.,
       1.0680561237549337e+03, 5.5693821427066280e+02, 0., 0., 1. ]
distortionCoefficients: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 4.0403537419643677e-02, -1.8850131673369398e-02,
       2.2666058394713523e-03, 2.1452074250293118e-03,
       -2.0779845401099672e-02 ]
rotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]
projection: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1.0678176639391463e+03, 0., 9.8017834376380301e+02, 0., 0.,
       1.0680561237549337e+03, 5.5693821427066280e+02, 0., 0., 0., 1.,
       0., 0., 0., 0., 1. ]

...
How do I take these values and utilize them in lieu of the factory calibrated values?

Thank you for any help you may offer!

**Comment by floe** [comment]
I think that's not an issue with your hardware, that's a fundamental geometric limitation. I remember a similar discussion in libfreenect1: https://github.com/OpenKinect/libfreenect/pull/347 
Since there are some pixels that only the depth camera can see, but not the color camera and vice versa, there will always be some pixel duplication unless you apply a depth filter.

**Comment by xlz** [comment]
Based on @larshg's implementation I added the depth filter to remove depth pixels that can't be seen by the RGB camera

2015-05-06-132923_1920x1080_scrot

The code is here https://github.com/xlz/libfreenect2/tree/registration

**Pull request merged**
