### PR TITLE
[WIB] Added methods to query for serialNumber and Camera parameters without starting device.

### PR DESCRIPTION
**Pull request by larshg**
Without the need of "starting" the device.

To prepare for reducing the start() method to only do what it is supposed to do - start streaming?

### CODE REVIEW

**Comment by larshg** [comment]
@christiankerl aren't they already in Freenect2DeviceImpl? Should they not be virtual - Should I change the IR/ColorCameraParams to be pointers instead - to check if they have a valid value? It's not that easy to validate if the struct itself is valid?

**Comment by floe** [comment]
I just realized that this will break when merged on top of the updated ColorCameraParams structure - sorry. Could you please re-submit based on current master?

**Comment by floe** [comment]
I'm a bit confused: PRs #68 and #82 somehow seem to have mixed? I think this is because they share some commits. @larshg can you somehow separate those two again, or close #82 and re-submit (I think due to the registration stuff having been merged in the meantime, #82 needs to be edited anyway - sorry).

**Comment by floe** [comment]
I'm pretty certain we can now close this - although I'm not quite sure how, the functions implemented by this PR are already part of master:libfreenect2.cpp with slightly different names (`getSerialNumber`, `getColor/IrCameraParams`).

**Comment by larshg** [comment]
They functions you mention has been around for ages. What I was trying to implement was to query the parameters without having to start the device. Right now the values are all read out in the start method, which should only start the actual streaming? right now it does multiple things.

**Comment by floe** [comment]
Aaah, sorry. OK, now I get it. In this case, could you amend your PR so that your functions are used within `Freenect2DeviceImpl::start`? Otherwise, we'd have a pretty big chunk of duplicate code.

**Comment by larshg** [comment]
Yes ofc. But I was i doubt about how to proceed, as there is no reason to Query the device each time, but only the first time. So should I make the various structs as a pointer and make a check for null-pointer? or should we just query the device each time?

**Comment by floe** [comment]
I think we don't need to mess around with additional pointers; for the serial number, we could check if it's the empty string, for intrinsics, we could check if fx == 0.0.

So e.g. `querySerialNumber` doesn't return anything (`void`), but stores the result in `serial_`, and in `getSerialNumber`, add `if (serial_.empty()) querySerialNumber();` before. Finally, in `start()`, we just call all three query functions so the fields are definitely populated as soon as the device is running.

Sounds reasonable?

**Comment by larshg** [comment]
Yes, also possible way to do it.

I just wanted to remove the Query/qet methods from the start method, so it in end only does one thing, ie start the streaming.

So when the registration is created, the getColorParams calls queryColor and afterwards you can start/stop, without doing any "new" readings of the params from the device.

ofc its minimal overhead in this and maybe its unreasonable to spent time on it?

**Comment by floe** [comment]
No, I think it is still reasonable to call them in start(), because you never know if some application might first start the device and then retrieve the serial number or intrinsics later, possibly even from another thread. And if you submit the USB query commands right in the middle of the regular data stream, who knows what other ugly USB3 issues might suddenly happen...

**Comment by larshg** [comment]
If we should still call them in start I don't see any reason to move it out from the start. So I'll close this one.

**Pull request closed without merging**
