### PR TITLE
Added FindLibrary files for various libraries

### PR DESCRIPTION
**Pull request by larshg**
Instead of hard coding in a sub depend folder.

Updated to to use PKG-config first to find and fallback to Cmake if pkg-config is not found.

I have only tested it on windows.

### CODE REVIEW

**Comment by larshg** [comment]
Updated this a lot to work with recent master and making first use of PKG-config as requested by @goldhoorn.

How are the various libraries located on Linux?
All headers in /usr/include
and libraries in /lib/?

**Comment by goldhoorn** [comment]
(short answer)

The core-concept:
reallce core os stuff:
/lib
/include
user stuff:
/usr/include/
/usr/lib/
machine-local user stuff:
/usr/local/include/
/usr/local/lib/

and so on..

But moreworese the distributions install in different sub-folder, thats what pkg-config was intended for. The user can give a multiple base-paths for package-config (.pc) files. The pc-file is generated during the build of these libraries and points to the correct paths. These paths are then used by cmake...

**Comment by larshg** [comment]
Hey
This has now been updated to match both my needs and @goldhoorn  - so if people could try it out and give feedback would be nice.

@christiankerl Can you review it?

There might be needed some paths updates in the Linux part, since I haven't yet installed a linux test machine. This is only if the libraries are not found by pkg-config though.

Lars

**Comment by goldhoorn** [comment]
I successfully tested this PR on Ubuntu 14.04 and Debian testing with all dependancies installed externally (either by apt-get or by providing the related pkg-config files (which are part of the libs itself).

Ack for merge from my side

**Comment by floe** [comment]
Sorry for the long silence, was just preparing to merge this, but has it been tested on MacOS X so far?

**Comment by goldhoorn** [comment]
I don't have a macos currently sorry :-(

**Comment by xlz** [comment]
I've looked at the patch. It is getting quite complicated, to which extent it is probably not worth the complexity to make a single cmake script work on both Windows and Linux. 

Building on Windows without package management or IDE is always an ad-hoc process (downloading tarballs, building stuff in MSVC and using it here, setting up environment parameters etc.) which requires a lot of help from documentation. Without hardcoded paths, it is just pushing the configuration of dependency libraries to cmake command line and to the documentation (which doesn't say anything right now about paths of these dependency libraries).

I have a build workflow on Windows which involves some manual work but works fine, submitted here #208. This will surely break it, but where are the new build instructions?

I recommend splitting this PR to two or more commits. The first one covers pkg-config on Linux and Mac. The second and more commits use separate cmake files to support building on Windows and include documentation about how to use it.

**Comment by larshg** [comment]
I think any other opensource projects manage to have a single Cmakefile to work with both Windows and linux - why shouldn't libfreenect2 be able to that also?

One could argue if it is worth the complexity to use both pkg-config and cmake.

When you install programs/libraries they will normally install in a default path, hence many of the libraries should be found with relatively few predefined paths, but if they aren't found here, one can specificy a "Library_Root" in enviroment variables if they are installed a custom place.

Your build flow forces people to have installed various libraries in a subfolder of libfreenect2, which seems unreasonable to me atleast. Why should I have opencv etc installed in libfreenect2, when I have it already in my "libraries" directory. And if I use an installer it is again installed in a (often) predefined path.

@goldhoorn and I have spent some time to get it working on both our ends, but this is still a work that needs proper testing - atleast I found some errors when trying to locate 32 bits libraries, so some adjustments is needed.

I guess we can start on a install guideline before this is merged, but I just haven't had the time yet :)

**Comment by xlz** [comment]
libfreenect2 is surely able to integrate Windows build script with one CMake file. The problem is if that is worth the complexity it adds to other platforms:

The model of package management and library linking on Windows are inherently a mess without an IDE. There is no centralized `/usr/lib64`. Users can install libraries to anywhere they want, but still need to be able to include it, and link it. Using an environment variable `Library_Root` or even `PATH` is one way to do it. Specifying the path of each individual library is another way. Asking users to copy the libraries to places specified in documentation is another way. All of them are not automated because of the nature of package management on Windows. And after compilation, you still need more setup of linking paths to make `Protonect` able to run. I don't see which one is better than another. But it is not the job of libfreenect2 to enforce a centralized global filesystem hierarchy. 

My proposed workflow is CMake-centric. You can install OpenCV anywhere you want, only need to specify `-DOpenCV_DIR=` for CMake as there is no CMake infrastructure on Windows. You do have to specify a installation path asked by libturbojpeg installer, then it makes sense to put it in the same place as on Mac OS. All of this has been documented in the instructions.

I still do not know how one would build libfreenect2 after this PR. Perhaps your workflow is Visual Studio-centric.

**Comment by goldhoorn** [comment]
I'm open for a general cleanup. But i don't want to break the "orginial way" how this package was created before.

One statement in  general i don't like the old way. A package should never download dependencies on it's own. This is part of the toolchains and higher level build tools like <a href="https://rubygems.org/gems/autoproj/versions/1.13.0">autoproj</a> <a href="http://wiki.ros.org/catkin">catkin</a> or whatever exist. I know where also on windows a find-library (Cmake find-sciripts) way is used. That is what this file like https://github.com/OpenKinect/libfreenect2/pull/68/files#diff-6cabc0d244512d70770162fd66ec036bR11 already ment for. 

I'm open to remove all the automatic dep handling and only use some variables. But since i'm not a windows user here i'm willing to maintaining/testing the linux part. But i need another person who takes the responsibility for windows. 

As transition phase, i recommend a build script which downloads all deps and install them. This would make the installaiton on windows easier. But from my point of view it's not the role of cmake. @floe and me only kept the existing behaviour because it's the decition of the package owner/developer in the end and i don't enforce people to follow my guidelines.

My summay: i'm open to do a complete cleanup and adding variables that can be used on windows. But if I (on my own) do this cleanup i will remove all automatic downloading and fixed path behavior.

**Comment by goldhoorn** [comment]
So i would really like to have  reply from @wiedemeyer, @christiankerl, @floe, @larshg  HOW this package should be used. And how the build system should look like.

**Comment by xlz** [comment]
I agree the install_deps.sh script is a temporary hack for before proper distro maintainer scripts and packages.

My objections were largely about complicating the code with multi-platform support `if() else()` everywhere. The end result is that Windows installation is still not quite automated but the code gets really complicated.

I did not get specific about the issues with the current patch. I will comment on the diff page.

**Comment by xlz** [comment]
It turns out given ideal environment setup (libusb, glfw, turbojpeg all have pkgconfig files) on Linux, the new cmake modules in this patch (FindTJPEG.cmake, FindLibUsb.cmake, FindGLFW3.cmake) are totally unused.

If the configuration logic in these modules is designed to be Windows/Mac only and isolated from pkgconfig infrastructure under Linux, I am fine with the current structure. The `auto_detect_lib()` macro is a bit confusing in that it can fall back to non pkgconfig condition under Linux, and fall into the mess of compatibility glue.

**Comment by xlz** [comment]
What is going on here? Previous coding comments are all lost. Are they fixed? Or not an issue?

**Comment by larshg** [comment]
Hmm, seems it has removed them after I did a rebase/force push - for those I didn't managed to change - for some reason they are not saved like these comments. I'll stop doing rebase/squash until all things are sorted...

I'm currently working on a build instruction too and there are a few things I need to look at (whether to download certain versions/installers) versus getting the newest with git clones of various projects. Also, they seem to be packed differently whether they are distributed in their packages or build/installed.

**Comment by larshg** [comment]
Comments still available [here] (https://github.com/larshg/libfreenect2/commit/3591b21600194abcc06237ab1068bb8841e8cf19#commitcomment-11326781).

**Comment by larshg** [comment]
Updated according to @xlz comments.

**Comment by goldhoorn** [comment]
So i would like to ask how the state is for this PR, i checked the current state of this PR inside my bootstrapping framework and it is working as expected. So for me it's fine to merge...

**Comment by floe** [comment]
Ah, good to know, thanks. I will test it one final time tomorrow on my setup (not in the office today), and then merge.

**Comment by goldhoorn** [comment]
I tested only for Linux on debian (so far) but if i have issues on other distribution i will create a PR after this got merged otherwise we will never finish this :+1:

**Comment by floe** [comment]
Finally merged! Thanks for your contributions, everyone, and sorry this took so long...

**Comment by floe** [comment]
*sigh* of course, about 5 minutes after the merge, I'm running into an error: when I don't have libusb-1.0-0-dev installed, but only the one from the depends/ folder, then I get this error message:

    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    LibUSB_INCLUDE_DIR
    used as include directory in directory /home/floe/src/libfreenect2.git/examples/protonect
    used as include directory in directory /home/floe/src/libfreenect2.git/examples/protonect
    used as include directory in directory /home/floe/src/libfreenect2.git/examples/protonect

A few lines earlier, however, cmake states:

    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
    -- checking for module 'libusb-1.0'
    --   found libusb-1.0, version 1.0.19
    -- checking for module 'opencv'
    --   found opencv, version 2.4.8

So it seems to find the correct pkgconfig file from depends/, but doesn't work if there's no system-wide installation of libusb-1.0?

**Comment by goldhoorn** [comment]
I using only the system wide install in debian this works with the kinect well

**Comment by floe** [comment]
On Debian, what's the exact path & name of the libusb-1.0 pkgconfig file?

**Comment by xlz** [comment]
Debian stretch/sid, `install_ubuntu.sh` local dependencies, no libusb-1.0-0-dev, I got this:
```
-- checking for module 'libusb'
--   package 'libusb' not found
CMake Error at /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  CMakeLists.txt:6 (pkg_check_modules)
  CMakeLists.txt:51 (auto_detect_lib)
```

The pkgconfig file is installed at `depends/libusb/lib/pkgconfig/libusb-1.0.pc`.

Ubuntu 14.04, `install_ubuntu.sh` local dependencies, cmake 2.8.12.2. libusb is not found as above, also:
```
-- checking for module 'glfw3'
--   package 'glfw3' not found
CMake Error at CMakeLists.txt:135 (if):
  if given arguments:

    "STREQUAL" "FALSE"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
```

**Comment by floe** [comment]
I think instead of `auto_detect_lib(LibUSB ...`, we need `auto_detect_lib(LibUSB-1.0 ...` in CMakeLists.txt, line 51. Also, some way of specifying the depends/ folder as fallback location still seems to be missing, I thought that was part of the patch?

@larshg could you quickly send an additional PR fixing these?

**Comment by gaborpapp** [comment]
I could not make this work in OSX with the master branch yet. Relying on `pkg-config` might not work there. I tried packages installed from macports, but I'm investigating further.

**Comment by goldhoorn** [comment]
Snip:
```
[11:01:47 goldhoorn orogen]$ dpkg -L libusb-dev | grep .pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libusb.pc
```

more info:
```
[11:03:28 goldhoorn orogen]$ dpkg -l libusb-dev
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name                                 Version                 Architektur             Beschreibung
+++-====================================-=======================-=======================-=============================================================================
ii  libusb-dev                           2:0.1.12-24             amd64                   userspace USB programming library development files
```

**Comment by goldhoorn** [comment]
Finally some infos regarding the found:
```
[11:05:12 goldhoorn build]$ cat CMakeCache.txt  | grep -i libusb
LibUSB_INCLUDE_DIR:PATH=/usr/include/libusb-1.0
LibUSB_CFLAGS:INTERNAL=
LibUSB_CFLAGS_I:INTERNAL=
LibUSB_CFLAGS_OTHER:INTERNAL=
LibUSB_FOUND:INTERNAL=1
LibUSB_INCLUDEDIR:INTERNAL=/usr/include
LibUSB_INCLUDE_DIRS:INTERNAL=
LibUSB_LDFLAGS:INTERNAL=-lusb
LibUSB_LDFLAGS_OTHER:INTERNAL=
LibUSB_LIBDIR:INTERNAL=/usr/lib/x86_64-linux-gnu
LibUSB_LIBRARIES:INTERNAL=usb
LibUSB_LIBRARY_DIRS:INTERNAL=
LibUSB_LIBS:INTERNAL=
LibUSB_LIBS_L:INTERNAL=
LibUSB_LIBS_OTHER:INTERNAL=
LibUSB_LIBS_PATHS:INTERNAL=
LibUSB_PREFIX:INTERNAL=/usr
LibUSB_STATIC_CFLAGS:INTERNAL=
LibUSB_STATIC_CFLAGS_I:INTERNAL=
LibUSB_STATIC_CFLAGS_OTHER:INTERNAL=
LibUSB_STATIC_INCLUDE_DIRS:INTERNAL=
LibUSB_STATIC_LDFLAGS:INTERNAL=-lusb
LibUSB_STATIC_LDFLAGS_OTHER:INTERNAL=
LibUSB_STATIC_LIBDIR:INTERNAL=
LibUSB_STATIC_LIBRARIES:INTERNAL=usb
LibUSB_STATIC_LIBRARY_DIRS:INTERNAL=
LibUSB_STATIC_LIBS:INTERNAL=
LibUSB_STATIC_LIBS_L:INTERNAL=
LibUSB_STATIC_LIBS_OTHER:INTERNAL=
LibUSB_STATIC_LIBS_PATHS:INTERNAL=
LibUSB_VERSION:INTERNAL=0.1.12
LibUSB_libusb_INCLUDEDIR:INTERNAL=
LibUSB_libusb_LIBDIR:INTERNAL=
LibUSB_libusb_PREFIX:INTERNAL=
LibUSB_libusb_VERSION:INTERNAL=
__pkg_config_checked_LibUSB:INTERNAL=1
```

**Comment by xlz** [comment]
@goldhoorn 
We should be using libusb-1.0-0-dev instead of libusb-dev?
```
libusb-1.0-0-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/libusb-1.0.pc
```

**Comment by gaborpapp** [comment]
OSX errors:

```
-- checking for module 'libusb'
--   package 'libusb' not found
CMake Error at /opt/local/share/cmake-3.2/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /opt/local/share/cmake-3.2/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  CMakeLists.txt:6 (pkg_check_modules)
  CMakeLists.txt:51 (auto_detect_lib)
```

libusb is installed, but macports does not provide a pkgconfig file for it.

```
CMake Error at cmake_modules/FindTurboJPEG.cmake:18 (message):
Could not find turbojpeg.h - Try define TurboJPEG_ROOT as a system
variable
```
Even when `TurboJPEG_ROOT` is set to `depends/libjpeg_turbo/`.

**Comment by goldhoorn** [comment]
@xlz  however it's simliar

```
[11:16:14 goldhoorn rock.core]$ dpkg -L libusb-1.0-0-dev
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libusb-1.0-0-dev
/usr/share/doc/libusb-1.0-0-dev/changelog.Debian.gz
/usr/share/doc/libusb-1.0-0-dev/changelog.gz
/usr/share/doc/libusb-1.0-0-dev/copyright
/usr/share/doc/libusb-1.0-0-dev/README
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libusb-1.0.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libusb-1.0.pc
/usr/include
/usr/include/libusb-1.0
/usr/include/libusb-1.0/libusb.h
/usr/lib/x86_64-linux-gnu/libusb-1.0.so
```

**Comment by larshg** [comment]
@gaborpapp can you try set TurboJPEG_ROOT to the full path? That's what the root environment variables are for.

@floe I only have a windows running atm. but I am semi working on getting a linux eviroment working also - but for now thats more @goldhoorn area in this pr.

I'll add the depends/"libraries" paths to all the findLibrary cmake files soonish.

**Comment by goldhoorn** [comment]
I'm in standby for testing ping me, but not have (yet) the time to contribute actively.

**Comment by gaborpapp** [comment]
@larhsg `TurboJPEG_ROOT` was set to the full path. I just meant it pointed to the `depends/libjpeg_turbo` directory.

**Comment by larshg** [comment]
@gaborpapp whats the subfolder in libjpeg_turbo? bin,classes,doc,include and lib?

**Comment by gaborpapp** [comment]
something like that, yes.
```
libjpeg_turbo
├── bin
├── include
├── lib
├── man
└── share
```

**Comment by larshg** [comment]
@gaborpapp I just relooked the find cmake script for libjpegturbo and it didn't look in the enviroment path variable.

I have added changes here https://github.com/larshg/libfreenect2/tree/FixFindLibJPEG - can you try it out?

**Comment by gaborpapp** [comment]
@larshg now it works for turbojpeg. thanks. would be nice to have a fallback location in the depends folder for the other libs as well if the `pkg-config` check fails, which still happens on OSX for `libusb`.

**Comment by larshg** [comment]
I guess if you can set an environment variable that would be fine? We can also add the depend folder as a search path until/if the depends get removed at some time - what do you think @floe ?

I'll look at the libusb also @gaborpapp - its also your local depends folder? - whats the folder structure for include and lib directory?

**Comment by floe** [comment]
Yes, I would suggest to simply put depends/libusb and depends/glfw into the search path for the time being. I think it will take a while until we can drop the dedicated libusb build.

**Comment by larshg** [comment]
oki and the 3 libraries are expected to be placed in depends with these subfolders: libjpeg_turbo, libusb and glfw? I'll add those 3 paths in their respective findlib cmake files.

**Comment by gaborpapp** [comment]
yes, if it works with an environment variable, that is fine. Maybe a bit easier to work with if the folders are in the search path as @floe suggests.

`libusb` was installed with `macports` just like `glfw` and `opencv`. the output from `pkg-config`:

```
$ pkg-config --list-all | grep 'glfw\|opencv\|libusb'
opencv                              OpenCV - Open Source Computer Vision Library
libusb-1.0                          libusb-1.0 - C API for USB device access from Linux, Mac OS X, Windows and OpenBSD/NetBSD userspace
glfw3                               GLFW - A multi-platform library for OpenGL, window and input
```
maybe it is because the `libusb-1.0`?

It is also in the depends folder, because I ran `install_deps.sh`/`install_mac.sh`.
Folder structure in depends for `libusb`:
```
libusb
├── include
└── lib
```

**Comment by floe** [comment]
Just to clarify, will it still work on Windows if I just rename LibUSB to LibUSB-1.0?

**Comment by larshg** [comment]
if works if you also rename the cmake for locating liusb. ie. findlibusb.cmake to findlibusb-1.0.cmake.

**Comment by goldhoorn** [comment]
Can you guys create a experimental branch on the repro so that we can 
test this?

**Comment by floe** [comment]
I've pushed a new branch `cmake_libusb_1.0` to the main repository.

**Comment by larshg** [comment]
The branch works fine on my setup.

**Comment by goldhoorn** [comment]
No i'm completely confused i don't have a kinect at my hand just now.
The proposed branch is compiling but links to another libusb version.
I don't know if this version had the required patches:

Current chosen one (with patch):
/lib/x86_64-linux-gnu/libusb-1.0.so.0.1.0
https://packages.debian.org/jessie/libusb-1.0-0

Previously choosen:
/lib/x86_64-linux-gnu/libusb-0.1.so.4.4.4
https://packages.debian.org/jessie/libusb-0.1-4

These packages are a mess...

**Comment by wiedemeyer** [comment]
With the current master or libusb branch I always get this error
```
CMake Error at CMakeLists.txt:151 (if):
  if given arguments:
    "STREQUAL" "FALSE"
  Unknown arguments specified
```
sovled it by checking if defined `if(NOT DEFINED ${GLFW3_FOUND} OR ${GLFW3_FOUND} STREQUAL "FALSE")`

The other problem is, that it now uses the system libusb, with is version 1.0.17. This version does not contain the needed patch. So there need to be a check for the version, for everything lower than 1.0.19-1  (or what ever is says on debian) use the one from the depends folder.

**Comment by floe** [comment]
Please check new branch `glfw3_fix`.

**Comment by larshg** [comment]
Works fine here.

**Comment by floe** [comment]
@larshg good to know, thanks.
@goldhoorn right now, there is no existing ready-made package which actually contains the exact libusb version we require. You can successfully compile and link libfreenect against libusb-1.0.17 and 1.0.19, but at runtime, you still need the custom-built libusb-1.0.so for things to work.

**Comment by gaborpapp** [comment]
@floe, if there's no working `libusb` why does `cmake` search for it instead of using the one in `depends`?

OSX build issues with the current master:

I had to set `TurboJPEG_ROOT` manually, `cmake` didn't fall back to `depends\libjpeg_turbo`.
Although `libusb` is picked up now, there's an error with `LIBUSB_INCLUDE_DIR`.

```
$ export TurboJPEG_ROOT=full-path-to/depends/libjpeg_turbo
$ cmake ..
-- The C compiler identification is AppleClang 6.0.0.6000057
-- The CXX compiler identification is AppleClang 6.0.0.6000057
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test LIBFREENECT2_THREADING_STDLIB
-- Performing Test LIBFREENECT2_THREADING_STDLIB - Failed
-- using tinythread as threading library
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.28") 
-- checking for module 'libusb-1.0'
--   found libusb-1.0, version 1.0.18
-- checking for module 'opencv'
--   found opencv, version 2.4.11
-- TurboJPEG_INCLUDE_DIR = full-path-to/depends/libjpeg_turbo/include
-- Performing Test TURBOJPEG_WORKS
-- Performing Test TURBOJPEG_WORKS - Success
-- TurboJPEG_LIBRARY = full-path-to/depends/libjpeg_turbo/lib/libturbojpeg.a
-- checking for module 'glfw3'
--   found glfw3, version 3.1.2
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework  
Linking with these libraries: opencv_calib3d;opencv_contrib;opencv_core;opencv_features2d;opencv_flann;opencv_gpu;opencv_highgui;opencv_imgproc;opencv_legacy;opencv_ml;opencv_nonfree;opencv_objdetect;opencv_photo;opencv_stitching;opencv_superres;opencv_ts;opencv_video;opencv_videostab;full-path-to/depends/libjpeg_turbo/lib/libturbojpeg.a;pthread;glfw;/System/Library/Frameworks/OpenCL.framework
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LibUSB_INCLUDE_DIR
   used as include directory in directory full-path-to/examples/protonect
   used as include directory in directory full-path-to/examples/protonect
   used as include directory in directory full-path-to/examples/protonect

-- Configuring incomplete, errors occurred!
See also "full-path-to/examples/protonect/build/CMakeFiles/CMakeOutput.log".
See also "full-path-to/examples/protonect/build/CMakeFiles/CMakeError.log".
```

**Comment by floe** [comment]
@gaborpapp The libusb install in `depends` also has a pkgconfig file, so it should be picked up first, at least when the search path is in the right order. I don't really know what to make of the LibUSB error message right now, though...

**Comment by larshg** [comment]
@gaborpapp I have added include and lib to the search path for depends folder - can you try #260 ?

Maybe the pkg-config sets another variable than LibUSB_INCLUDE_DIR - can you see what name it is @gaborpapp - then we can rename the scripts accordingly. It could be LibUSB_INCLUDE_DIRS?

**Comment by hanyazou** [comment]
@larshg pkg_check_modules macro provides only <XPREFIX>_INCLUDE_DIRS. (Not _DIR but _DIRS.)

**Comment by gaborpapp** [comment]
@larshg grepping CMakeCache.txt for libusb gives these lines, which seem relevant. although this is still the libusb installed on the system instead of the one in depends.

```
CMakeCache.txt:LIBUSB_INCLUDE_DIRS:PATH=LIBUSB_INCLUDE_DIRS-NOTFOUND
CMakeCache.txt:LibUSB_INCLUDE_DIR:PATH=LibUSB_INCLUDE_DIR-NOTFOUND
CMakeCache.txt:LibUSB-1.0_INCLUDEDIR:INTERNAL=/opt/local/include
CMakeCache.txt:LibUSB-1.0_INCLUDE_DIRS:INTERNAL=/opt/local/include/libusb-1.0
```

**Comment by xlz** [comment]
@larshg 
So much breakage for Linux and Mac.

Can you document your workflow? Even if I want to fix your cmake files and have a Windows machine to test, I still don't know what you intended for [this kind of stuff](https://github.com/OpenKinect/libfreenect2/blob/master/examples/protonect/cmake_modules/FindLibUsb-1.0.cmake#L21) here ("libusb-win32 is a port of the USB library ​libusb-0.1", we never used libusb-0.1), and I don't know how to avoid breaking your workflow.

**Pull request merged**
