### PR TITLE
Adding in CLI -help and -version options

### PR DESCRIPTION
**Pull request by RyanGordon**
Thought it would make sense to add in a version string into the library/Protonect CLI output. The -help option just displays the stderr output that's been written at the beginning of main and subsequently exits. I can refactor it more but I thought I'd keep the changes simple for now and open this for feedback.

### CODE REVIEW

**Comment by xlz** [comment]
```
if(arg == "-help" || arg == "--help" || arg == "-h" ||
  arg == "-v" || arg == "--version" || arg == "-version")
```

config.h.in:
```
#define LIBFREENECT2_VERSION "@PROJECT_VER@"
#define LIBFREENECT2_API_VERSION ((@PROJECT_VER_MAJOR@ << 16) | @PROJECT_VER_MINOR@)
```

**Comment by xlz** [comment]
This should go to the stable branch as a hotfix because this version macro is kind of required in all version in order to provide certain compatibility.

**Comment by xlz** [comment]
@floe

**Comment by RyanGordon** [comment]
@xlz Thanks for the feedback. Fixed in 71d32df and I also moved device discovery down below the args parsing so that it doesn't happen if we specify --help or --version. I also added --noviewer to the args list for consistent but didn't give it a shorthard

**Comment by RyanGordon** [comment]
Addressed your comments here: ad3f2b1

**Comment by floe** [comment]
OK, agreed. I'll fix the CONTRIB file afterwards and tag v0.1.1.

**Comment by floe** [comment]
@xlz should this be cherry-picked into master? Original PR was relative to v0.1 branch.

**Comment by xlz** [comment]
It was done.

**Pull request merged**
