### PR TITLE
Fix CMake's UPPERCASE_FOUND package detection and resulting segfaults

### LINKED ISSUE #564: Turbojpeg not detected by default, resulting in Segmentation Fault
Hi,

I am trying to run install libfreenect2 and run the Protonect executable. However I keep getting Segmentation Fault. Both infrared and xbox logo light up and don turn off after I ry to run the example. During the first try a black window appears for half a second then it closes  with the segmentation fault message.

Here are both outputs of both calling Protonect and dmesg...

Thanks for your help.

```
Version: 0.1.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./Protonect [gl | cl | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
To pause and unpause: pkill -USR1 Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 14 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:8 with serial 038870245147
[Info] [Freenect2Impl] found 1 devices
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Debug] [Freenect2DeviceImpl] status 0x090000: 9729
[Debug] [Freenect2DeviceImpl] status 0x090000: 9731
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
device serial: 038870245147
device firmware: 4.0.3911.0
[Debug] [DepthPacketStreamParser] not all subsequences received 0
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [DepthPacketStreamParser] skipping depth packet
Segmentation fault (core dumped)
```

```
[332468.676039] usb 1-4: new high-speed USB device number 18 using xhci_hcd
[332468.989284] usb 2-4: new SuperSpeed USB device number 7 using xhci_hcd
[332469.173894] usb 1-4: New USB device found, idVendor=045e, idProduct=02d9
[332469.173898] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[332469.173900] usb 1-4: Product: NuiSensor Adaptor      
[332469.173902] usb 1-4: Manufacturer: Microsoft Corporation  
[332469.174503] hub 1-4:1.0: USB hub found
[332469.174751] hub 1-4:1.0: 1 port detected
[332471.967960] usb 2-4: New USB device found, idVendor=045e, idProduct=02d9
[332471.967963] usb 2-4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[332471.967965] usb 2-4: Product: NuiSensor Adaptor      
[332471.967967] usb 2-4: Manufacturer: Microsoft Corporation  
[332471.970057] hub 2-4:1.0: USB hub found
[332471.970207] hub 2-4:1.0: 1 port detected
[332472.436132] usb 2-4.1: new SuperSpeed USB device number 8 using xhci_hcd
[332472.452757] usb 2-4.1: New USB device found, idVendor=045e, idProduct=02c4
[332472.452763] usb 2-4.1: New USB device strings: Mfr=1, Product=2, SerialNumber=4
[332472.452766] usb 2-4.1: Product: Xbox NUI Sensor
[332472.452768] usb 2-4.1: Manufacturer: Microsoft
[332472.452771] usb 2-4.1: SerialNumber: 038870245147
[332494.368248] usb 2-4.1: reset SuperSpeed USB device number 8 using xhci_hcd
[332494.384421] xhci_hcd 0000:00:14.0: xHCI xhci_drop_endpoint called with disabled ep ffff88085654cc00
[332494.384425] xhci_hcd 0000:00:14.0: xHCI xhci_drop_endpoint called with disabled ep ffff88085654cc48
[332494.384426] xhci_hcd 0000:00:14.0: xHCI xhci_drop_endpoint called with disabled ep ffff88085654ccd8
[332494.384427] xhci_hcd 0000:00:14.0: xHCI xhci_drop_endpoint called with disabled ep ffff88085654cc90
[332495.387063] Protonect[26892]: segfault at 0 ip 00007f4c85583527 sp 00007f4c75808e90 error 4 in libfreenect2.so.0.1.0[7f4c85574000+3b000] ```

### PR DESCRIPTION
**Pull request by xlz**
Fix #564.

@fran6co

### CODE REVIEW

**Comment by fran6co** [comment]
Looks good

**Comment by floe** [comment]
I'll cherry-pick to 0.1 afterwards?

**Comment by xlz** [comment]
@floe TurboJPEG is always required in 0.1 so this bug is not exposed.

**Comment by floe** [comment]
Oh, I got confused by the original bug report because the log showed 0.1.0. Could you update the version in master branch while you're at it?

**Pull request merged**
