### PR TITLE
Usb error reporting

### PR DESCRIPTION
**Pull request by xlz**
* Properly stop execution when usb errors happen (libusb errors, short command response).
* Use std::vector instead of manual memory management in CommandTransaction

### CODE REVIEW

**Comment by floe** [comment]
This does look very sensible. As this would only affect the internal API/ABI, it might be worth considering as bugfix for 0.1.2?

**Comment by xlz** [comment]
Maybe. The bug this is fixing is segfault after usb failure. This merely makes it nicer to handle, but the user still has to stop the entire program upon such errors.

**Comment by xlz** [comment]
v2: `min_response_length` was added to the wrong structure (`CommandData` instead of `CommandBase`) which is sent over USB. This messed up the byte protocol. Fix it.

**Comment by xlz** [comment]
Now tested on Debian and Windows.

@RyanGordon @fran6co I'll merge this PR next week. If you have time, please try it on Mac.

**Comment by fran6co** [comment]
Seems to be working ok on Mac. Didn't get any error to test the full scope of it, though.

**Comment by xlz** [comment]
Manually merged.

**Pull request closed without merging**
