### PR TITLE
commented out unused variable from cpu_depth_packet_processor.cpp

### PR DESCRIPTION
**Pull request by gaborpapp**
Can this be removed or something more complex is missing?

### CODE REVIEW

**Comment by floe** [comment]
Since this is a leftover of the conversion from shader to CPU code, I'd prefer to just comment it out.

**Comment by xlz** [comment]
Just leave it and compiler will optimize it out for you.

**Comment by gaborpapp** [comment]
Sure, but it gives a warning every time I compile the code, which is not very elegant.

**Comment by gaborpapp** [comment]
Commented the variable out instead as you prefer.

**Comment by floe** [comment]
Yeah, I think that's the best solution. Merged.

**Pull request merged**
