### PR TITLE
removes unused memory allocation in the registration

### PR DESCRIPTION
**Pull request by giacomodabisias**
I think its quite useless and expensive to allocate memory at every registration step.

### CODE REVIEW

**Comment by fran6co** [comment]
Isn't this PR moving an allocation from heap to stack?

**Comment by giacomodabisias** [comment]
should be less expensive since the compiler can optimize everything, while in the other case we have to make a dynamic allocation.

**Comment by wiedemeyer** [comment]
I try to avoid creating large arrays on the stack, because it could lead to problems with the maximum stack size.

**Comment by giacomodabisias** [comment]
I think there should be no problems with allocating on stack such a structure since it is not really big:
512*424*4bytes=848Kbyte
Dynamically allocating it is not nice if you use the grabber online at a high rate.

**Comment by giacomodabisias** [comment]
What about putting it in the registration class as mutable so the user can decide where to allocate it? :)

**Comment by wiedemeyer** [comment]
Right now all the variables in the registration class are only accessed reading from the methods, so you are able to run multiple calls in parallel. If you make it a member, you have to use a mutex to protect it.
Another solution would be to add another pointer to the parameters. If the pointer is null a new array will be allocated and deleted at the end, but if it's not null, it will use that array (and the user has to make sure that it is large enough). Or maybe a reference/pointer to a `std::vector`.
Anyway, is there a real speedup compared to the current implementation? And what do the others think?

**Comment by giacomodabisias** [comment]
I agree 100% with you, but I think it would be nice to be able to decide
how to allocate it. I like the second solution you proposed (pointer).
Il 21/ott/2015 18:09, "Thiemo Wiedemeyer" <notifications@github.com> ha
scritto:

**Comment by xlz** [comment]
Allocating 848KB is definitely not OK. MSVC default stack size is 1MB.

I agree allocating 848KB 30 times per second is not optimal. But I don't think registration is performance bottleneck right now.

**Comment by giacomodabisias** [comment]
So what about the pointer solution like with the bigdepth frame?

**Comment by xlz** [comment]
I guess the solution is changing the interface to let user provide the intermediate data structure.

**Comment by giacomodabisias** [comment]
I will do a pull request and then we can discuss about it

**Comment by floe** [comment]
Is there any use for `depth_to_c_off` outside of `apply`? I don't think that one malloc/free per frame will make any measurable difference, the size of the allocation doesn't matter.

**Comment by giacomodabisias** [comment]
Probably not, but In my opinion its nice to have the user decide it.

**Comment by floe** [comment]
Closing in favor of #441.

**Pull request closed without merging**
