### PR TITLE
removed GLEW dependency and use OpenGL function loader generated with flextGL

### PR DESCRIPTION
**Pull request by christiankerl**
this removes the dependency on GLEW which caused some problems

before merging this, it should be tested on different platforms:

- [x] Ubuntu 12.04, 14.04 with NVIDIA GPU
- [ ] MacOSX with NVIDIA GPU
- [x] Windows 7 with ATI GPU
- [x] Windows 8.1 with NVIDIA GPU
- [ ] ...

### CODE REVIEW

**Comment by larshg** [comment]
Hi @christiankerl 

I have tested this addition on my dell precision m6600 with ATI firepro m8900 GPU and it works.

Regards, Lars

**Comment by christiankerl** [comment]
@larshg Windows or which OS?

**Comment by larshg** [comment]
Woops, Yes - its windows 7 :)

**Comment by wiedemeyer** [comment]
Ubuntu 14.04.1 (Linux version 3.16.0-29-generic with nvidia) works fine!

**Comment by larshg** [comment]
Hey

I have now tested it on my windows 8.1 pc with nvidia GTX 480 gpu.

I could only test the opengl part and it worked fine :+1: 

I could however not test the opencl part and I'm running out of time for testing - Is opencl supported with the cuda toolkit or is it necessary with some 3. party - just like opencv does?

Regards, Lars

**Comment by wiedemeyer** [comment]
This change only effects OpenGL and should not have any effects on OpenCL.

**Comment by christiankerl** [comment]
fixes #136

**Pull request merged**
