### PR TITLE
Assorted fixes and cleanup for 0.1

### PR DESCRIPTION
**Pull request by xlz**
* Incorporate various CMake best practices bug fixes
* Enforce libusb 1.0.20 requirement on Linux
* Improve Visual Studio 2013/2015 build support, automatically copy DLLs to executables
* Fix OpenGL 3.1 Windows support (tested on a i3-2330M with 15fps depth/30fps rgb)
* Improve OpenCL compatibility (solve #139, #250, #167)
* Documentation updates, including changes to workflow

Build tested on Debian (gcc 5, cmake 3.3, Intel), Ubuntu (gcc 4.8, cmake 2.8.12, Intel), Windows 7 (VS2013, Intel), WIndows 8.1 (VS2015, Intel), Ubuntu (gcc 4.8, cmake 2.8.12, ARM).

I think the commits are all quite small but functional.

### CODE REVIEW

**Comment by xlz** [comment]
Tests OK on all of Debian (gcc 5, cmake 3.3, Intel), Ubuntu (gcc 4.8, cmake 2.8.12, Intel), Windows 7 (VS2013, Intel), WIndows 8.1 (VS2015, Intel), Ubuntu (gcc 4.8, cmake 2.8.12, ARM).

@fran6co Could you test this on a Mac? Thanks.

**Comment by fran6co** [comment]
I'll have to test it on Monday, I don't have a Kinect2 right now.

**Comment by xlz** [comment]
Reviews for this PR:

@christiankerl This PR changes `glBindFramebuffer(GL_DRAW_FRAMEBUFFER,...)` to `GL_FRAMEBUFFER` to fix one of FBO completeness requirements which is enforced only on OpenGL 3.1 not later. See if this looks OK.

@wiedemeyer This PR adds a local copy of cl.hpp to the repo and no longer downloads it. This will probably solve the once ugly `undef CL_VERSION_1_2` hack. See if this practice is OK.

@larshg @HenningJ This PR improves Visual Studio support. It should automatically copy DLLs for both debugging and installation. Is this feature that you wanted? Also, now that I have a Windows machine for Kinect, I can fix more issues related to Visual Studio.

**Comment by fran6co** [comment]
It builds ok, I'll give it a run on Monday.

**Comment by xlz** [comment]
@fran6co Thanks. Especially the OpenGL part which still has error reports recently.

**Comment by fran6co** [comment]
Tested the OpenGL depth processor and it's working ok on OS X 10.11.

**Comment by xlz** [comment]
So now the testing coverage if full.

Is it time to drop support for Ubuntu 12.04 precise (cmake 2.8.7, no libusb 1.0.20, no beignet-dev 1.0) and document that?

**Comment by floe** [comment]
Yes, I think 12.04 can be considered outdated now.

**Comment by floe** [comment]
Will test soon, however, merge conflict with #379?

**Comment by xlz** [comment]
Conflict in CMakeLists.txt. Rebased.

**Comment by xlz** [comment]
I changed README "libusbK driver" section to remind Windows users not to make mistakes installing the driver. Resolves #448 #425.

**Comment by floe** [comment]
@xlz thanks again for your work! I'll now close the related issues.

**Comment by lishirui** [comment]
Thanks @xlz  , @floe  and everyone who contribute this code and fix bugs

**Pull request merged**
