### PR TITLE
added --dump option for exporting input data for test_opengl

### LINKED ISSUE #112: test_opengl crashes while loading ptable's
in OSX 10.9.5.

error in console:
```
[OpenGLDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 0 from './../p00.bin' failed!
[OpenGLDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 1 from './../p01.bin' failed!
[OpenGLDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 2 from './../p02.bin' failed!
[CpuDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 0 from './../p00.bin' failed!
[CpuDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 1 from './../p01.bin' failed!
[CpuDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 2 from './../p02.bin' failed!
libc++abi.dylib: terminating with uncaught exception of type std::exception: std::exception
```

The files don't exists. Are they removed or should be generated somehow?

backtrace:
```
* thread #1: tid = 0x3bab4, 0x00007fff97599866 libsystem_kernel.dylib`__pthread_kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff97599866 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff98e0235c libsystem_pthread.dylib`pthread_kill + 92
    frame #2: 0x00007fff97556b1a libsystem_c.dylib`abort + 125
    frame #3: 0x00007fff95e18f31 libc++abi.dylib`abort_message + 257
    frame #4: 0x00007fff95e3e93a libc++abi.dylib`default_terminate_handler() + 240
    frame #5: 0x00007fff8c648322 libobjc.A.dylib`_objc_terminate() + 124
    frame #6: 0x00007fff95e3c1d1 libc++abi.dylib`std::__terminate(void (*)()) + 8
    frame #7: 0x00007fff95e3bc5b libc++abi.dylib`__cxa_throw + 124
    frame #8: 0x0000000100008d80 test_opengl`loadBufferFromFile(filename=<unavailable>, buffer=<unavailable>, n=<unavailable>) + 624 at test_opengl_depth_packet_processor.cpp:43
    frame #9: 0x00000001000092f4 test_opengl`main(argc=<unavailable>, argv=<unavailable>) + 1140 at test_opengl_depth_packet_processor.cpp:100
    frame #10: 0x00007fff8e2a85fd libdyld.dylib`start + 1
```

### PR DESCRIPTION
**Pull request by gaborpapp**
closes #112

### CODE REVIEW

**Comment by floe** [comment]
Looks good for me, but since it's changing some internals, maybe @christiankerl can weigh in?

**Comment by christiankerl** [comment]
Well. My suggestion would be to create a separate binary. E.g. dumprawir implement a simple depthpacketprocessor subclass which just dumps the data. Finally create a custom packet pipeline based on basepacketpipeline you only need to implement one method. This can be done in a single CPP file. I would really appreciate if you make the effort and implement it this way instead of adapting the cpudepthpacketprocessor. Thanks!

**Comment by gaborpapp** [comment]
We discussed how we address this in #112, but your suggestion seems cleaner. I'll try to do it in this way then.

**Comment by christiankerl** [comment]
Sorry for not commenting earlier, but I'm little busy lately

**Comment by gaborpapp** [comment]
another try in #169, closing this.

**Pull request closed without merging**
