### PR TITLE
Extended name of libtubrojpeg for debian packaging

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by floe** [comment]
Wouldn't libturbojpeg.so.1 instead of .so.0 indicate a newer version of the package with different ABI?

**Comment by goldhoorn** [comment]
On 17.06.2015 15:06, Florian Echtler wrote:
>
> Wouldn't libturbojpeg.so.1 instead of .so.0
>
that what the PR is. (regard naiming)
>
> indicate a newer version of the package with different ABI?
>
> —
>
I think debian marks their stable/unstable packages this way.
however i compiled successfully against this versions so no EABI 
incompatibility can occur.

Tested on debian stable/unstable/testing and ubuntu 14.04 and 15.04

**Comment by floe** [comment]
OK, I'll merge it, but please add a comment that .so.1 is from Debian Jessie(?) and .so.0 is from Ubuntu 14/15. Otherwise, when the Ubuntu packages will update at some point, then .so.1 will point to a different versions on Ubuntu, possibly breaking things.

**Comment by floe** [comment]
OK, thanks (you could also have pushed an additional commit to this PR, BTW).

**Comment by goldhoorn** [comment]
Whos i thoug you merged _this_ one. sorry ;) too much prs from me going around ;)

**Comment by xlz** [comment]
Debian's libturbojpeg{0,1} provide libturbojpeg.so. There is no need to work around it.

https://packages.debian.org/jessie/amd64/libturbojpeg1-dev/filelist
https://packages.debian.org/stretch/amd64/libturbojpeg0-dev/filelist
https://packages.debian.org/sid/amd64/libturbojpeg0-dev/filelist

**Comment by goldhoorn** [comment]
I saw this on the homepae too, however our standard build server (no 
mods in the OS) tells me something different where without this patch 
the build is failing...

Best,
Matthias

**Comment by xlz** [comment]
What exactly is the something different? Can we debug it?

**Pull request merged**
